### PR TITLE
Fix utxo chains

### LINKED ISSUE #77: [BUG] Transaction signatures for Bitcoin and Doge stay in Vulticonnect’s “signing in” loading animation forever
## Description

With the **Vulticonnect extension in its most recent version of the main branch** when I try to make a transaction in BTC or DOGE the extension gets stuck in the sign-in window. 

## Steps to reproduce

Broadcast DOGE transaction with memo: 

`+:DOGE.DOGE::yi:0`

(tomorrow will add video THORChain networks is halted now)

## Expected behaviour

The confirmation window should pop up when the transaction has been sent to the network.

## Actual behaviour

The loading window remains forever even if the transaction has reached the network.

## Logs and Screenshots

Screenshot 2024-12-12 at 13 43 27

### LINKED ISSUE #78: [BUG] When a non-EVM the Vulticonnect extension throws a validation error in the console
## Description

After connecting a non-EVM address to my Dapp via Vulticonnect I get an error on every reload that seems to come from the extension code itself.

## Steps to reproduce

1. Detect a non-EVM string to a Dapp.
2. Reload the page
3. Inspect the browser console

## Expected behaviour

No error should be displayed in the console

## Actual behaviour

The error appears after each reload until the extension is 'unlinked'

## Logs and Screenshots

image

### LINKED ISSUE #79: [BUG] Activating the Vultisig prioritization option causes an infinite loop of listener registrations
## Description

When I activate the Vulticonnect prioritization option I start to receive a warning of an excess of registered listeners. This error does not appear without this extension option enabled.  

## Steps to reproduce

1. Enable option 'Prioritize VultiConnect'
2. Refresh the Dapp
3. Check warning in browser console

## Expected behaviour

It should work in the same way as when not prioritized. 

## Actual behaviour

If I activate it, the performance problem generated makes my application slow.

## Logs and Screenshots

image

### LINKED ISSUE #81: [BUG] Small fee amount formatting
Chains with small fees need an improved formatting for display.
Example dydx:
image

### LINKED ISSUE #82: [BUG] Network fee without unit
It is not visible what kind of unit is used for displaying network fees, happens on all chains:

image

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
Fix #77 
Fix #78 
Fix #79 

Fix #81 
Fix #82

### CODE REVIEW

File: utils/constants.ts [hunk 1]
```diff
@@ -248,6 +246,10 @@ export const rpcUrl: ChainRpcRef = {
   [ChainKey.POLYGON]: "https://polygon-bor-rpc.publicnode.com",
   [ChainKey.ZKSYNC]: "https://mainnet.era.zksync.io",
   [ChainKey.THORCHAIN]: "https://rpc.ninerealms.com/",
+  [ChainKey.GAIACHAIN]: "https://cosmos-rpc.publicnode.com:443",
```
Comment (johnnyluo) [inline utils/constants.ts:249]: you don't need to specify port for https , could you remove it?

**Review by johnnyluo — APPROVED** [review]
LGTM
